"""Initial migration

Revision ID: 47706da5fff4
Revises: 
Create Date: 2024-11-03 09:47:57.220670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47706da5fff4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
